var sourcesIndex = JSON.parse('{\
"iced":["",[["window",[],["icon.rs","position.rs","settings.rs"]]],["application.rs","clipboard.rs","element.rs","error.rs","executor.rs","keyboard.rs","lib.rs","mouse.rs","overlay.rs","result.rs","sandbox.rs","settings.rs","time.rs","touch.rs","widget.rs","window.rs"]],\
"iced_core":["",[["keyboard",[],["event.rs","key_code.rs","modifiers.rs"]],["mouse",[],["button.rs","event.rs","interaction.rs"]]],["alignment.rs","background.rs","color.rs","content_fit.rs","font.rs","keyboard.rs","length.rs","lib.rs","mouse.rs","padding.rs","point.rs","rectangle.rs","size.rs","time.rs","vector.rs"]],\
"iced_futures":["",[["backend",[["native",[],["async_std.rs","smol.rs","thread_pool.rs","tokio.rs"]]],["default.rs","native.rs","null.rs"]],["subscription",[],["tracker.rs"]]],["backend.rs","command.rs","executor.rs","lib.rs","maybe_send.rs","runtime.rs","subscription.rs"]],\
"iced_glow":["",[["image",[],["storage.rs"]],["quad",[],["compatibility.rs","core.rs"]],["window",[],["compositor.rs"]]],["backend.rs","image.rs","lib.rs","program.rs","quad.rs","settings.rs","text.rs","triangle.rs","window.rs"]],\
"iced_glutin":["",[],["application.rs","lib.rs"]],\
"iced_graphics":["",[["font",[],["source.rs"]],["gradient",[],["linear.rs"]],["image",[],["raster.rs","storage.rs","vector.rs"]],["layer",[],["image.rs","mesh.rs","quad.rs","text.rs"]],["overlay",[],["menu.rs"]],["widget",[["canvas",[["path",[],["arc.rs","builder.rs"]]],["cache.rs","cursor.rs","event.rs","fill.rs","frame.rs","geometry.rs","path.rs","program.rs","stroke.rs","style.rs","text.rs"]]],["canvas.rs","qr_code.rs"]],["window",[],["compositor.rs","gl_compositor.rs"]]],["antialiasing.rs","backend.rs","error.rs","font.rs","gradient.rs","image.rs","layer.rs","lib.rs","overlay.rs","primitive.rs","renderer.rs","transformation.rs","triangle.rs","viewport.rs","widget.rs","window.rs"]],\
"iced_lazy":["",[],["cache.rs","component.rs","lazy.rs","lib.rs","responsive.rs"]],\
"iced_native":["",[["command",[],["action.rs"]],["debug",[],["basic.rs"]],["layout",[],["flex.rs","limits.rs","node.rs"]],["mouse",[],["click.rs"]],["overlay",[],["element.rs","group.rs","menu.rs"]],["program",[],["state.rs"]],["renderer",[],["null.rs"]],["system",[],["action.rs","information.rs"]],["widget",[["image",[],["viewer.rs"]],["operation",[],["focusable.rs","scrollable.rs","text_input.rs"]],["pane_grid",[],["axis.rs","configuration.rs","content.rs","direction.rs","draggable.rs","node.rs","pane.rs","split.rs","state.rs","title_bar.rs"]],["text_input",[],["cursor.rs","editor.rs","value.rs"]]],["action.rs","button.rs","checkbox.rs","column.rs","container.rs","helpers.rs","id.rs","image.rs","operation.rs","pane_grid.rs","pick_list.rs","progress_bar.rs","radio.rs","row.rs","rule.rs","scrollable.rs","slider.rs","space.rs","svg.rs","text.rs","text_input.rs","toggler.rs","tooltip.rs","tree.rs","vertical_slider.rs"]],["window",[],["action.rs","event.rs","mode.rs","redraw_request.rs","user_attention.rs"]]],["clipboard.rs","command.rs","element.rs","event.rs","hasher.rs","image.rs","keyboard.rs","layout.rs","lib.rs","mouse.rs","overlay.rs","program.rs","renderer.rs","runtime.rs","shell.rs","subscription.rs","svg.rs","system.rs","text.rs","touch.rs","user_interface.rs","widget.rs","window.rs"]],\
"iced_style":["",[["theme",[],["palette.rs"]]],["application.rs","button.rs","checkbox.rs","container.rs","lib.rs","menu.rs","pane_grid.rs","pick_list.rs","progress_bar.rs","radio.rs","rule.rs","scrollable.rs","slider.rs","svg.rs","text.rs","text_input.rs","theme.rs","toggler.rs"]],\
"iced_wgpu":["",[["buffer",[],["dynamic.rs","static.rs"]],["image",[["atlas",[],["allocation.rs","allocator.rs","entry.rs","layer.rs"]]],["atlas.rs"]],["triangle",[],["msaa.rs"]],["window",[],["compositor.rs"]]],["backend.rs","buffer.rs","image.rs","lib.rs","quad.rs","settings.rs","text.rs","triangle.rs","window.rs"]],\
"iced_winit":["",[["application",[],["profiler.rs","state.rs"]],["settings",[],["other.rs"]]],["application.rs","clipboard.rs","conversion.rs","error.rs","lib.rs","position.rs","proxy.rs","settings.rs","system.rs","window.rs"]]\
}');
createSourceSidebar();
