var sourcesIndex = JSON.parse('{\
"iced":["",[["window",[],["icon.rs","position.rs","settings.rs"]]],["advanced.rs","application.rs","error.rs","lib.rs","sandbox.rs","settings.rs","time.rs","window.rs"]],\
"iced_core":["",[["keyboard",[],["event.rs","key_code.rs","modifiers.rs"]],["layout",[],["flex.rs","limits.rs","node.rs"]],["mouse",[],["button.rs","click.rs","cursor.rs","event.rs","interaction.rs"]],["overlay",[],["element.rs","group.rs"]],["renderer",[],["null.rs"]],["widget",[["operation",[],["focusable.rs","scrollable.rs","text_input.rs"]]],["id.rs","operation.rs","text.rs","tree.rs"]],["window",[],["event.rs","icon.rs","level.rs","mode.rs","redraw_request.rs","user_attention.rs"]]],["alignment.rs","angle.rs","background.rs","border_radius.rs","clipboard.rs","color.rs","content_fit.rs","element.rs","event.rs","font.rs","gradient.rs","hasher.rs","image.rs","keyboard.rs","layout.rs","length.rs","lib.rs","mouse.rs","overlay.rs","padding.rs","pixels.rs","point.rs","rectangle.rs","renderer.rs","shell.rs","size.rs","svg.rs","text.rs","time.rs","touch.rs","vector.rs","widget.rs","window.rs"]],\
"iced_futures":["",[["backend",[["native",[],["async_std.rs","smol.rs","thread_pool.rs","tokio.rs"]]],["default.rs","native.rs","null.rs"]],["subscription",[],["tracker.rs"]]],["backend.rs","executor.rs","lib.rs","maybe_send.rs","runtime.rs","subscription.rs"]],\
"iced_graphics":["",[["geometry",[["path",[],["arc.rs","builder.rs"]]],["fill.rs","path.rs","stroke.rs","style.rs","text.rs"]]],["antialiasing.rs","backend.rs","color.rs","compositor.rs","damage.rs","error.rs","geometry.rs","gradient.rs","image.rs","lib.rs","primitive.rs","renderer.rs","transformation.rs","viewport.rs"]],\
"iced_renderer":["",[["geometry",[],["cache.rs"]]],["backend.rs","compositor.rs","geometry.rs","lib.rs","settings.rs"]],\
"iced_runtime":["",[["command",[],["action.rs"]],["debug",[],["basic.rs"]],["overlay",[],["nested.rs"]],["program",[],["state.rs"]],["system",[],["action.rs","information.rs"]],["window",[],["action.rs"]]],["clipboard.rs","command.rs","font.rs","keyboard.rs","lib.rs","overlay.rs","program.rs","system.rs","user_interface.rs","window.rs"]],\
"iced_style":["",[["theme",[],["palette.rs"]]],["application.rs","button.rs","checkbox.rs","container.rs","lib.rs","menu.rs","pane_grid.rs","pick_list.rs","progress_bar.rs","radio.rs","rule.rs","scrollable.rs","slider.rs","svg.rs","text_input.rs","theme.rs","toggler.rs"]],\
"iced_tiny_skia":["",[["window",[],["compositor.rs"]]],["backend.rs","geometry.rs","lib.rs","raster.rs","settings.rs","text.rs","vector.rs","window.rs"]],\
"iced_wgpu":["",[["image",[["atlas",[],["allocation.rs","allocator.rs","entry.rs","layer.rs"]]],["atlas.rs","raster.rs","vector.rs"]],["layer",[],["image.rs","mesh.rs","text.rs"]],["quad",[],["gradient.rs","solid.rs"]],["triangle",[],["msaa.rs"]],["window",[],["compositor.rs"]]],["backend.rs","buffer.rs","geometry.rs","image.rs","layer.rs","lib.rs","quad.rs","settings.rs","text.rs","triangle.rs","window.rs"]],\
"iced_widget":["",[["canvas",[],["event.rs","program.rs"]],["image",[],["viewer.rs"]],["lazy",[],["cache.rs","component.rs","helpers.rs","responsive.rs"]],["overlay",[],["menu.rs"]],["pane_grid",[],["axis.rs","configuration.rs","content.rs","direction.rs","draggable.rs","node.rs","pane.rs","split.rs","state.rs","title_bar.rs"]],["text_input",[],["cursor.rs","editor.rs","value.rs"]]],["button.rs","canvas.rs","checkbox.rs","column.rs","container.rs","helpers.rs","image.rs","lazy.rs","lib.rs","mouse_area.rs","overlay.rs","pane_grid.rs","pick_list.rs","progress_bar.rs","qr_code.rs","radio.rs","row.rs","rule.rs","scrollable.rs","slider.rs","space.rs","svg.rs","text.rs","text_input.rs","toggler.rs","tooltip.rs","vertical_slider.rs"]],\
"iced_winit":["",[["application",[],["profiler.rs","state.rs"]],["settings",[],["other.rs"]]],["application.rs","clipboard.rs","conversion.rs","error.rs","lib.rs","position.rs","proxy.rs","settings.rs","system.rs"]]\
}');
createSourceSidebar();
