var srcIndex = new Map(JSON.parse('[\
["iced",["",[["window",[],["icon.rs"]]],["advanced.rs","application.rs","daemon.rs","error.rs","lib.rs","program.rs","settings.rs","time.rs","window.rs"]]],\
["iced_core",["",[["keyboard",[],["event.rs","key.rs","location.rs","modifiers.rs"]],["layout",[],["flex.rs","limits.rs","node.rs"]],["mouse",[],["button.rs","click.rs","cursor.rs","event.rs","interaction.rs"]],["overlay",[],["element.rs","group.rs"]],["renderer",[],["null.rs"]],["text",[],["editor.rs","highlighter.rs","paragraph.rs"]],["theme",[],["palette.rs"]],["widget",[["operation",[],["focusable.rs","scrollable.rs","text_input.rs"]]],["id.rs","operation.rs","text.rs","tree.rs"]],["window",[["settings",[],["linux.rs"]]],["event.rs","icon.rs","id.rs","level.rs","mode.rs","position.rs","redraw_request.rs","settings.rs","user_attention.rs"]]],["alignment.rs","angle.rs","background.rs","border.rs","clipboard.rs","color.rs","content_fit.rs","element.rs","event.rs","font.rs","gradient.rs","image.rs","keyboard.rs","layout.rs","length.rs","lib.rs","mouse.rs","overlay.rs","padding.rs","pixels.rs","point.rs","rectangle.rs","renderer.rs","rotation.rs","shadow.rs","shell.rs","size.rs","svg.rs","text.rs","theme.rs","time.rs","touch.rs","transformation.rs","vector.rs","widget.rs","window.rs"]]],\
["iced_futures",["",[["backend",[["native",[],["async_std.rs","smol.rs","thread_pool.rs","tokio.rs"]]],["default.rs","native.rs","null.rs"]],["subscription",[],["tracker.rs"]]],["backend.rs","event.rs","executor.rs","keyboard.rs","lib.rs","maybe.rs","runtime.rs","stream.rs","subscription.rs"]]],\
["iced_graphics",["",[["geometry",[["path",[],["arc.rs","builder.rs"]]],["cache.rs","fill.rs","frame.rs","path.rs","stroke.rs","style.rs","text.rs"]],["text",[],["cache.rs","editor.rs","paragraph.rs"]]],["antialiasing.rs","cache.rs","color.rs","compositor.rs","damage.rs","error.rs","geometry.rs","gradient.rs","image.rs","layer.rs","lib.rs","mesh.rs","settings.rs","text.rs","viewport.rs"]]],\
["iced_highlighter",["",[],["lib.rs"]]],\
["iced_renderer",["",[],["fallback.rs","lib.rs"]]],\
["iced_runtime",["",[["debug",[],["basic.rs"]],["multi_window",[],["program.rs","state.rs"]],["overlay",[],["nested.rs"]],["program",[],["state.rs"]],["window",[],["screenshot.rs"]]],["clipboard.rs","font.rs","keyboard.rs","lib.rs","multi_window.rs","overlay.rs","program.rs","system.rs","task.rs","user_interface.rs","window.rs"]]],\
["iced_tiny_skia",["",[["window",[],["compositor.rs"]]],["engine.rs","geometry.rs","layer.rs","lib.rs","primitive.rs","raster.rs","settings.rs","text.rs","vector.rs","window.rs"]]],\
["iced_wgpu",["",[["image",[["atlas",[],["allocation.rs","allocator.rs","entry.rs","layer.rs"]]],["atlas.rs","cache.rs","mod.rs","raster.rs","vector.rs"]],["quad",[],["gradient.rs","solid.rs"]],["triangle",[],["msaa.rs"]],["window",[],["compositor.rs"]]],["buffer.rs","color.rs","engine.rs","geometry.rs","layer.rs","lib.rs","primitive.rs","quad.rs","settings.rs","text.rs","triangle.rs","window.rs"]]],\
["iced_widget",["",[["canvas",[],["event.rs","program.rs"]],["image",[],["viewer.rs"]],["keyed",[],["column.rs"]],["lazy",[],["cache.rs","component.rs","helpers.rs","responsive.rs"]],["overlay",[],["menu.rs"]],["pane_grid",[],["axis.rs","configuration.rs","content.rs","direction.rs","draggable.rs","node.rs","pane.rs","split.rs","state.rs","title_bar.rs"]],["shader",[],["event.rs","program.rs"]],["text_input",[],["cursor.rs","editor.rs","value.rs"]]],["button.rs","canvas.rs","checkbox.rs","column.rs","combo_box.rs","container.rs","helpers.rs","image.rs","keyed.rs","lazy.rs","lib.rs","mouse_area.rs","overlay.rs","pane_grid.rs","pick_list.rs","progress_bar.rs","qr_code.rs","radio.rs","row.rs","rule.rs","scrollable.rs","shader.rs","slider.rs","space.rs","stack.rs","svg.rs","text.rs","text_editor.rs","text_input.rs","themer.rs","toggler.rs","tooltip.rs","vertical_slider.rs"]]],\
["iced_winit",["",[["program",[],["state.rs","window_manager.rs"]]],["clipboard.rs","conversion.rs","error.rs","lib.rs","program.rs","proxy.rs","settings.rs","system.rs"]]]\
]'));
createSrcSidebar();
